easy_admin:
  entities:
    Comment:
      class: Kader\CommentBundle\Entity\Comment
      list:
        fields:
          - id
          - author
          - content
          - context
          - createdAt
      edit:
        fields:
          - author
          - content
